### ISSUE TITLE
can't build v1.1.4 due to incorrect path in module.xconfig

### ISSUE THREAD

**Issue by skoften** [jpriebe/ti.dfp#11]
You forgot to update the path from

FRAMEWORK_SEARCH_PATHS=$(SRCROOT)/../../modules/iphone/ti.dfp/1.1.3/platform

to

FRAMEWORK_SEARCH_PATHS=$(SRCROOT)/../../modules/iphone/ti.dfp/1.1.4/platform

So building the app fails...

**Comment by jpriebe** [comment]
It's funny -- I just noticed this today, and then I went into my github account and saw you'd opened this earlier.  I didn't notice before, because I had version 1.1.3 installed along with version 1.1.4, so things just kind of worked.

I've re-released 1.1.4, but that framework search path thing is a PITA.  Is there some way to put a token in that will automatically be substituted with the current version number?
